"""
testbench_exporter.py — Standalone testbench export for the AI pipeline path.

The non-AI complete_pipeline uses EquivalenceChecker._save_testbenches() to
write testbenches alongside equivalence checks.  This module provides the same
capability for pipeline.py (AI-only path), which never calls EquivalenceChecker.

Usage:
    from testbench_exporter import export_testbench
    tb_dir = export_testbench(
        va_code=va_code,
        spice_netlist=netlist_text,
        info=info,          # dict from parse_netlist()
        x=x, y=y,           # DC sweep arrays
        output_dir="./output_run",
    )

Output structure:
    output_dir/
      testbenches/
        {module_name}/
          testbench.sp        — ngspice-compatible standalone DC sweep testbench
          run_testbench.sh    — convenience shell script
"""

import re
from pathlib import Path


def export_testbench(va_code: str,
                     spice_netlist: str,
                     info: dict,
                     x,
                     y,
                     output_dir: str = ".") -> Path:
    """
    Write a standalone ngspice testbench for the generated VA model.

    Args:
        va_code:        Complete Verilog-AMS source string.
        spice_netlist:  Original SPICE netlist (used as the reference in comments).
        info:           Dict returned by parse_netlist(): signal_source, output_node,
                        vdd, dc_start, dc_stop, dc_step.
        x:              DC sweep input array  (numpy array or None).
        y:              DC sweep output array (numpy array or None).
        output_dir:     Root output directory; testbenches/ created inside it.

    Returns:
        Path to the created testbench directory.
    """
    module_name = _extract_module_name(va_code) or "behavioral_model"
    tb_root = Path(output_dir) / "testbenches" / module_name
    tb_root.mkdir(parents=True, exist_ok=True)

    # ── Determine sweep parameters ────────────────────────────────────
    start = info.get("dc_start") or 0.0
    stop  = info.get("dc_stop")  or info.get("vdd", 1.8)
    step  = info.get("dc_step")  or (stop - start) / 100
    sig   = info.get("signal_source", "vin")
    out   = info.get("output_node",   "vout")
    vdd   = info.get("vdd", 1.8)

    # ── Write testbench.sp ────────────────────────────────────────────
    tb_sp = _build_ngspice_testbench(
        module_name=module_name,
        va_code=va_code,
        signal_source=sig,
        output_node=out,
        vdd=vdd,
        dc_start=start,
        dc_stop=stop,
        dc_step=step,
        x=x,
        y=y,
    )
    tb_path = tb_root / "testbench.sp"
    tb_path.write_text(tb_sp)

    # ── Write run_testbench.sh ────────────────────────────────────────
    va_filename = f"{module_name}.va"
    sh = (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by SynapticAMS testbench_exporter\n"
        "set -e\n"
        f'SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"\n'
        f'cd "$SCRIPT_DIR"\n'
        f"# 1. Compile VA model with OpenVAF\n"
        f"openvaf {va_filename}\n"
        f"# 2. Run ngspice testbench\n"
        f'ngspice -b testbench.sp -o testbench.log\n'
        f'echo "Done. Check testbench.log for results."\n'
    )
    sh_path = tb_root / "run_testbench.sh"
    sh_path.write_text(sh)
    sh_path.chmod(0o755)

    # Copy VA file alongside testbench for self-contained export
    va_path = tb_root / va_filename
    va_path.write_text(va_code)

    print(f"      Testbench saved: {tb_root}/")
    return tb_root


# ── Helpers ────────────────────────────────────────────────────────────

def _extract_module_name(va_code: str) -> str | None:
    m = re.search(r'\bmodule\s+(\w+)', va_code)
    return m.group(1) if m else None


def _build_ngspice_testbench(module_name, va_code, signal_source, output_node,
                              vdd, dc_start, dc_stop, dc_step, x, y) -> str:
    """
    Build a standalone ngspice testbench that loads the VA model via OSDI.

    The testbench sweeps the input from dc_start to dc_stop and measures
    V(output_node).  Golden reference values from the SPICE simulation are
    embedded as comments so the engineer can compare by inspection.
    """
    golden = ""
    if x is not None and y is not None:
        import numpy as _np
        idx = _np.round(_np.linspace(0, len(x) - 1, min(10, len(x)))).astype(int)
        rows = "\n".join(f"* {x[i]:>10.4f}  {y[i]:>10.4f}" for i in idx)
        golden = (
            "* --- Golden reference (ngspice DC sweep) ---\n"
            "* Input (V)   Output (V)\n"
            + rows + "\n*\n"
        )

    return f"""\
* SynapticAMS — Standalone testbench for {module_name}
* Generated by testbench_exporter.py
*
* HOW TO RUN:
*   openvaf {module_name}.va          (compile VA → OSDI)
*   ngspice -b testbench.sp           (run simulation)
*
{golden}
* ── Supply and stimulus ──────────────────────────────────────────────
VDD  vdd  0  DC {vdd}
VIN  {signal_source}  0  DC 0

* ── Behavioral model instance ────────────────────────────────────────
* (requires {module_name}.osdi compiled by OpenVAF in the same directory)
.model {module_name}_mdl {module_name}
X1 {output_node} {signal_source} {module_name}_mdl

* ── Load ─────────────────────────────────────────────────────────────
RLOAD  {output_node}  0  1MEG

* ── Analysis ────────────────────────────────────────────────────────
.DC VIN {dc_start:.6g} {dc_stop:.6g} {dc_step:.6g}

* ── Output ──────────────────────────────────────────────────────────
.print DC V({output_node})

.END
"""
